name: DockerHub Push

on:
  release:
    types: [released]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t lok0613/futu-opend-docker:${{ github.event.release.tag_name }} .
      - run: docker push lok0613/futu-opend-docker:${{ github.event.release.tag_name }}

      - run: docker tag lok0613/futu-opend-docker:${{ github.event.release.tag_name }} lok0613/futu-opend-docker:latest
      - run: docker push lok0613/futu-opend-docker:latest
