name: DockerHub Push

on:
  create:
    tags:
      - v*

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t lok0613/futu-opend-docker:${GITHUB_REF/refs\/tags\//} .
      - run: |-
          docker push lok0613/futu-opend-docker:${GITHUB_REF/refs\/tags\//}

